# Generated by Django 5.2.2 on 2025-06-30 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(choices=[('red', 'red'), ('yellow', 'yellow'), ('orange', 'orange'), ('blue', 'blue')], max_length=6)),
                ('grade', models.CharField(choices=[('P', 'Primary'), ('M', 'Matthayom')], max_length=1)),
                ('grade_num1', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], max_length=1)),
                ('grade_num2', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], max_length=1)),
            ],
        ),
    ]
