# Generated by Django 5.2.2 on 2025-06-30 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='student',
            name='grade_num1',
        ),
        migrations.RemoveField(
            model_name='student',
            name='grade_num2',
        ),
    ]
