# Generated by Django 5.2.2 on 2025-07-02 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildboard', '0002_remove_student_grade_remove_student_grade_num1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(choices=[('red', 'red'), ('yellow', 'yellow'), ('orange', 'orange'), ('blue', 'blue')], max_length=6)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildboard.game')),
                ('members', models.ManyToManyField(to='buildboard.student')),
            ],
        ),
    ]
