# Generated by Django 5.2.4 on 2025-07-22 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildboard', '0003_game_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='status',
            field=models.CharField(choices=[('single', 'single'), ('pair', 'pair'), ('team', 'team')], max_length=6, null=True),
        ),
    ]
