# Generated by Django 5.2.4 on 2025-07-14 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_alter_event_date_alter_event_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='tournament',
        ),
        migrations.AddField(
            model_name='tournament',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tournament.event'),
        ),
    ]
