# Generated by Django 5.2.4 on 2025-07-19 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0007_tournament_name_alter_event_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_connect', to='tournament.tournament'),
        ),
    ]
